### ISSUE TITLE
Problems installing GPU version of niftynet on head node without GPU

### ISSUE THREAD

**Issue by twinkarma** [jade-hpc-gpu/jade-hpc-gpu.github.io#105]
pip installs all the packages fine but niftynet needs to import tensorflow that won't run without GPU but on the GPU nodes there's no internet connection.

@joshastley would you be able to post the run scripts and errors that you've encountered?

**Comment by joshastley** [comment]
I get the following error message whether i run the script on the head node or as a job. This makes sense for the head node as it is a CPU however this should work for the job script where a GPU is requested. For clarity installing the tensorflow-CPU version works on the head node and allows niftynet commands to be used.

jxa05-txk12@dgj419:~$ source activate tensorflow-gpu
(tensorflow-gpu) jxa05-txk12@dgj419:~$ net_download highres3dnet_brain_parcellation_model_zoo
Traceback (most recent call last):
  File "/jmain01/home/JAD009/txk12/jxa05-txk12/.conda/envs/tensorflow-gpu/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/jmain01/home/JAD009/txk12/jxa05-txk12/.conda/envs/tensorflow-gpu/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/jmain01/home/JAD009/txk12/jxa05-txk12/.conda/envs/tensorflow-gpu/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/jmain01/home/JAD009/txk12/jxa05-txk12/.conda/envs/tensorflow-gpu/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/jmain01/home/JAD009/txk12/jxa05-txk12/.conda/envs/tensorflow-gpu/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: /jmain01/home/JAD009/txk12/jxa05-txk12/.conda/envs/tensorflow-gpu/lib/python3.6/site-packages/tensorflow/python/../libtensorflow_framework.so: symbol cublasSetMathMode, version libcublas.so.9.0 not defined in file libcublas.so.9.0 with link time reference

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/jmain01/home/JAD009/txk12/jxa05-txk12/.conda/envs/tensorflow-gpu/lib/python3.6/site-packages/niftynet/__init__.py", line 15, in <module>
    import tensorflow as tf
  File "/jmain01/home/JAD009/txk12/jxa05-txk12/.conda/envs/tensorflow-gpu/lib/python3.6/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/jmain01/home/JAD009/txk12/jxa05-txk12/.conda/envs/tensorflow-gpu/lib/python3.6/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/jmain01/home/JAD009/txk12/jxa05-txk12/.conda/envs/tensorflow-gpu/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/jmain01/home/JAD009/txk12/jxa05-txk12/.conda/envs/tensorflow-gpu/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/jmain01/home/JAD009/txk12/jxa05-txk12/.conda/envs/tensorflow-gpu/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/jmain01/home/JAD009/txk12/jxa05-txk12/.conda/envs/tensorflow-gpu/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/jmain01/home/JAD009/txk12/jxa05-txk12/.conda/envs/tensorflow-gpu/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/jmain01/home/JAD009/txk12/jxa05-txk12/.conda/envs/tensorflow-gpu/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: /jmain01/home/JAD009/txk12/jxa05-txk12/.conda/envs/tensorflow-gpu/lib/python3.6/site-packages/tensorflow/python/../libtensorflow_framework.so: symbol cublasSetMathMode, version libcublas.so.9.0 not defined in file libcublas.so.9.0 with link time reference


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/jmain01/home/JAD009/txk12/jxa05-txk12/.conda/envs/tensorflow-gpu/bin/net_download", line 6, in <module>
    from niftynet.utilities.download import main
  File "/jmain01/home/JAD009/txk12/jxa05-txk12/.conda/envs/tensorflow-gpu/lib/python3.6/site-packages/niftynet/__init__.py", line 17, in <module>
    raise ImportError('NiftyNet is based on TensorFlow, which'
ImportError: NiftyNet is based on TensorFlow, which does not seem to be installed on your system.

Please install TensorFlow (https://www.tensorflow.org/) to be able to use NiftyNet.
