### ISSUE TITLE
Nvidia profiler - file creation issue

### ISSUE THREAD

**Issue by andygittings** [jade-hpc-gpu/jade-hpc-gpu.github.io#26]
Original message from Istvan Reguly:

I am having trouble using the nvidia visual profiler, as well as the command line profiler. If I get an interactive session, and ssh to that node with -X, and try to launch nvvp, I get the following error:

java.lang.RuntimeException: Error initializing storage.
at org.eclipse.osgi.internal.framework.EquinoxContainer.<init>(EquinoxContainer.java:77)
at org.eclipse.osgi.launch.Equinox.<init>(Equinox.java:31)
at org.eclipse.core.runtime.adaptor.EclipseStarter.startup(EclipseStarter.java:295)
at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:231)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:606)
at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:648)
at org.eclipse.equinox.launcher.Main.basicRun(Main.java:603)
at org.eclipse.equinox.launcher.Main.run(Main.java:1465)
at org.eclipse.equinox.launcher.Main.main(Main.java:1438)
Caused by: java.io.IOException: An error occurred while locking file "/jmain01/home/JAD013/sxg01/ixr17-sxg01/.eclipse/org.eclipse.platform_4.4.1_1378847358_linux_gtk_x86_64/configuration/org.eclipse.osgi/.manager/.fileTableLock": "Function not implemented". A common reason is that the file system or Runtime Environment does not support file locking for that location. Please choose a different location, or disable file locking by passing "-Dosgi.locking=none" as a VM argument.
at org.eclipse.osgi.internal.location.Locker_JavaNio.lock(Locker_JavaNio.java:49)
at org.eclipse.osgi.storagemanager.StorageManager.lock(StorageManager.java:388)
at org.eclipse.osgi.storagemanager.StorageManager.open(StorageManager.java:701)
at org.eclipse.osgi.storage.Storage.getChildStorageManager(Storage.java:1747)
at org.eclipse.osgi.storage.Storage.getInfoInputStream(Storage.java:1764)
at org.eclipse.osgi.storage.Storage.<init>(Storage.java:124)
at org.eclipse.osgi.storage.Storage.createStorage(Storage.java:84)
at org.eclipse.osgi.internal.framework.EquinoxContainer.<init>(EquinoxContainer.java:75)

If I try to use the command line profiler:
nvprof -o testing ./a.out
==29520== NVPROF is profiling process 29520, command: ./a.out
==29520== Error: Cannot create profiling file: /jmain01/home/JAD013/sxg01/ixr17-sxg01/testing

---------------

I have also tried this with a piece of test code and running the nvprof command on a node from an interactive session and see the same problem... e.g.

srun --partition=devel --gres=gpu:1 --pty /bin/bash  -l
module load cuda
nvprof -o testing ./test_cu8

=73608== NVPROF is profiling process 73608, command: ./test_cu8
==73608== Error: Cannot create profiling file: /jmain01/home/JAD001/mxs13/amg17-mxs13/bench/cuda9/cuda_course_2016/practicals/cuda_version/testing

**Comment by Parker-A** [comment]
The parallel is mounted without file lock in place.
Can you pass the parameters ""-Dosgi.locking=none" to the JVM as suggested by the error log ? 

We can look at remounting the filesystem with local locking in place, but this will require an outage.

**Comment by Parker-A** [comment]
We have re-mounted the filesystem on the "devel" node with the local locking parameter. It would be useful to try it out on this node if you can.

**Comment by andygittings** [comment]
Thanks - I've asked the users to give it a try on the devel node. I'll report back,

**Comment by reguly** [comment]
Apologies, I couldn't log on last night - this does seem to have resolved the issue. I am not sure how to pass JVM parameters, considering I just do the launch with "$> nvvp &"

**Comment by andygittings** [comment]
Also positive  results from another user that was seeing issues with file locking when using h5py. I asked him to try the devel node and it works there... So looks like it is worth rolling out.

**Comment by Parker-A** [comment]
Thanks for the feedback, we will update the image with the new settings and make sure all the nodes get the new mount options.
We just need to go ahead to upgrade the rest of the cluster now.

**Comment by martinjhnhadley** [comment]
My understanding is this should be fine now as all nodes have been updated?

**Comment by reguly** [comment]
This seems to be working well now, thank you!
