### ISSUE TITLE
Cuda devices unavailable with PyTorch 

### ISSUE THREAD

**Issue by ekazakos** [jade-hpc-gpu/jade-hpc-gpu.github.io#40]
Hi,

Im using PyTorch within the `big` partition, where Im using all the 8 GPUs of a computing node. Some times my program is running normally, but a lot of times I get the following error and then my program is terminated,

THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1518244421288/work/torch/lib/THC/THCStream.cpp line=40 error=46 : all CUDA-capable devices are busy or unavailable
Traceback (most recent call last):
  File "train.py", line 541, in <module>
    main()
  File "train.py", line 235, in main
    train(train_loader, model, criterion, optimizer, epoch)
  File "train.py", line 289, in train
    output = model(input_var)
  File "/jmain01/home/JAD026/dxd01/shared/miniconda3/envs/epic/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/jmain01/home/JAD026/dxd01/shared/miniconda3/envs/epic/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 69, in forward
    inputs, kwargs = self.scatter(inputs, kwargs, self.device_ids)
  File "/jmain01/home/JAD026/dxd01/shared/miniconda3/envs/epic/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 80, in scatter
    return scatter_kwargs(inputs, kwargs, device_ids, dim=self.dim)
  File "/jmain01/home/JAD026/dxd01/shared/miniconda3/envs/epic/lib/python3.6/site-packages/torch/nn/parallel/scatter_gather.py", line 38, in scatter_kwargs
    inputs = scatter(inputs, target_gpus, dim) if inputs else []
  File "/jmain01/home/JAD026/dxd01/shared/miniconda3/envs/epic/lib/python3.6/site-packages/torch/nn/parallel/scatter_gather.py", line 31, in scatter
    return scatter_map(inputs)
  File "/jmain01/home/JAD026/dxd01/shared/miniconda3/envs/epic/lib/python3.6/site-packages/torch/nn/parallel/scatter_gather.py", line 18, in scatter_map
    return list(zip(*map(scatter_map, obj)))
  File "/jmain01/home/JAD026/dxd01/shared/miniconda3/envs/epic/lib/python3.6/site-packages/torch/nn/parallel/scatter_gather.py", line 15, in scatter_map
    return Scatter.apply(target_gpus, None, dim, obj)
  File "/jmain01/home/JAD026/dxd01/shared/miniconda3/envs/epic/lib/python3.6/site-packages/torch/nn/parallel/_functions.py", line 73, in forward
    streams = [_get_stream(device) for device in ctx.target_gpus]
  File "/jmain01/home/JAD026/dxd01/shared/miniconda3/envs/epic/lib/python3.6/site-packages/torch/nn/parallel/_functions.py", line 73, in <listcomp>
    streams = [_get_stream(device) for device in ctx.target_gpus]
  File "/jmain01/home/JAD026/dxd01/shared/miniconda3/envs/epic/lib/python3.6/site-packages/torch/nn/parallel/_functions.py", line 101, in _get_stream
    _streams[device] = torch.cuda.Stream(device)
  File "/jmain01/home/JAD026/dxd01/shared/miniconda3/envs/epic/lib/python3.6/site-packages/torch/cuda/streams.py", line 21, in __new__
    return super(Stream, cls).__new__(cls, priority=priority, **kwargs)
RuntimeError: cuda runtime error (46) : all CUDA-capable devices are busy or unavailable at /opt/conda/conda-bld/pytorch_1518244421288/work/torch/lib/THC/THCStream.cpp:40

Could you please resolve this issue, as it results in my experiments being randomly terminated? Thanks.

**Comment by LiamATOS** [comment]
what node does it fail on?

is it hitting the same node and failing all the time?

When raising such requests, we need as much information as possible?

Job ID's, Job script etc

Thanks

Liam

**Comment by ekazakos** [comment]
It is an old issue that I dont have anymore. If I ever have it again I will
let you know.

I remember that it was happening in different nodes. Also, it was not
happening all the time, but occasionally.

You are right. Im sorry for providing inadequate information. The next time
that I will have such an issue I will provide you with as much information
as possible.

Best,

Vangelis Kazakos

2018-05-11 12:33 GMT+01:00 LiamATOS <notifications@github.com>:
