### ISSUE TITLE
tensorflow.python.framework.errors_impl.InternalError: Failed to create session.

### ISSUE THREAD

**Issue by llyhec** [jade-hpc-gpu/jade-hpc-gpu.github.io#63]
For the past few days I keep getting the following error when I try to run my keras job:  

  File "tester.py", line 204, in <module>
    buildmodel(input, msefile, classifierf, value)
  File "tester.py", line 47, in buildmodel
    autoencoder = load_model('my_modela.h5')
  File "/jmain01/apps/python3/keras/2.1.4/lib/python3.6/site-packages/Keras-2.1.4-py3.6.egg/keras/models.py", line 246, in load_model
  File "/jmain01/apps/python3/keras/2.1.4/lib/python3.6/site-packages/Keras-2.1.4-py3.6.egg/keras/engine/topology.py", line 3189, in load_weights_from_hdf5_group
  File "/jmain01/apps/python3/keras/2.1.4/lib/python3.6/site-packages/Keras-2.1.4-py3.6.egg/keras/backend/tensorflow_backend.py", line 2370, in batch_set_value
  File "/jmain01/apps/python3/keras/2.1.4/lib/python3.6/site-packages/Keras-2.1.4-py3.6.egg/keras/backend/tensorflow_backend.py", line 176, in get_session
  File "/jmain01/apps/python3/tensorflow/1.4.1/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1482, in __init__
    super(Session, self).__init__(target, graph, config=config)
  File "/jmain01/apps/python3/tensorflow/1.4.1/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 622, in __init__
    self._session = tf_session.TF_NewDeprecatedSession(opts, status)
  File "/jmain01/apps/python3/tensorflow/1.4.1/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InternalError: Failed to create session.

What's happening here? I do not think the problem is with my model, it was running perfectly well before.

**Comment by twinkarma** [comment]
Are you getting this problem consistently? Looks like this may be related to an ongoing problem where either the GPU lock's gone wrong or someone's batch script is not respecting the CUDA_VISIBLE_DEVICES flag allowing people to use GPUs they're not meant to.

Can you add the following lines to your batch script after you've loaded all the modules so that we can check ?

```
nvidia-smi
echo "Using CUDA device" $CUDA_VISIBLE_DEVICES
```

**Comment by llyhec** [comment]
I had this problem since the beginning of last week. However, last week I was able to run things occasionally, but, since Sunday evening until now this has been a consistent problem. I couldn't run anything on Sunday, Monday, Tuesday and this morning. I just submitted a job, and it is running. I added those lines to my script, and the output is as follows: 

```
 Python anaconda is now loaded in your environment.

python3/3.6.3(19):ERROR:150: Module 'python3/3.6.3' conflicts with the currently loaded module(s) 'python3/anaconda'
python3/3.6.3(19):ERROR:102: Tcl command execution failed: conflict python3


        CUDA-8.0 loaded


        Keras-2.1.4, Tensorflow-1.4.1 with Python3 and CUDA loaded.
        Check your $HOME/.tensorflowrc file is OK.

Wed Jul  4 15:08:53 2018
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 384.111                Driver Version: 384.111                   |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla P100-SXM2...  On   | 00000000:06:00.0 Off |                    0 |
| N/A   47C    P0   186W / 300W |   6865MiB / 16276MiB |     61%   E. Process |
+-------------------------------+----------------------+----------------------+
|   1  Tesla P100-SXM2...  On   | 00000000:07:00.0 Off |                    0 |
| N/A   39C    P0    36W / 300W |     10MiB / 16276MiB |      0%   E. Process |
+-------------------------------+----------------------+----------------------+
|   2  Tesla P100-SXM2...  On   | 00000000:0A:00.0 Off |                    0 |
| N/A   36C    P0    33W / 300W |     10MiB / 16276MiB |      0%   E. Process |
+-------------------------------+----------------------+----------------------+
|   3  Tesla P100-SXM2...  On   | 00000000:0B:00.0 Off |                    0 |
| N/A   36C    P0    33W / 300W |     10MiB / 16276MiB |      0%   E. Process |
+-------------------------------+----------------------+----------------------+
|   4  Tesla P100-SXM2...  On   | 00000000:85:00.0 Off |                    0 |
| N/A   38C    P0    34W / 300W |     10MiB / 16276MiB |      0%   E. Process |
+-------------------------------+----------------------+----------------------+
|   5  Tesla P100-SXM2...  On   | 00000000:86:00.0 Off |                    0 |
| N/A   31C    P0    33W / 300W |     10MiB / 16276MiB |      0%   E. Process |
+-------------------------------+----------------------+----------------------+
|   6  Tesla P100-SXM2...  On   | 00000000:89:00.0 Off |                    0 |
| N/A   39C    P0    36W / 300W |     10MiB / 16276MiB |      0%   E. Process |
+-------------------------------+----------------------+----------------------+
|   7  Tesla P100-SXM2...  On   | 00000000:8A:00.0 Off |                    0 |
| N/A   34C    P0    34W / 300W |     10MiB / 16276MiB |      0%   E. Process |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0     31780      C   python                                      6855MiB |
+-----------------------------------------------------------------------------+


Using CUDA device 1
2018-07-04 15:10:00.044920: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that
this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2018-07-04 15:10:01.090481: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Found device 0 with properties:
name: Tesla P100-SXM2-16GB major: 6 minor: 0 memoryClockRate(GHz): 1.4805
pciBusID: 0000:07:00.0
totalMemory: 15.89GiB freeMemory: 15.60GiB
2018-07-04 15:10:01.090619: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1120]
Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: Tesla P100-SXM2-16GB,
pci bus id: 0000:07:00.0, compute capability: 6.0)
```

I will add this line to my other jobs and keep you updated. Thanks for your help.

**Comment by llyhec** [comment]
I tried to submit more jobs, now I am getting the following plugin error: 

`slurmstepd-dgj101: error: write(/dev/cpuset/slurm_dgj101_126113/slurm126113.4294967294_0/cpuset.cpus): Invalid argument
slurmstepd-dgj101: error: read(/dev/cpuset/slurm_dgj101_126113/slurm126113.4294967294_0/tasks): Invalid argument
slurmstepd-dgj101: error: Failed to invoke task plugins: task_p_pre_launch error
` 
 I submitted about 10 jobs, and I got the same error.

**Comment by llyhec** [comment]
And I got that error again this is the output from the script: 
```

python3/3.6.3(19):ERROR:150: Module 'python3/3.6.3' conflicts with the currently loaded module(s) 'python3/anaconda'
python3/3.6.3(19):ERROR:102: Tcl command execution failed: conflict python3


        CUDA-8.0 loaded


        Keras-2.1.4, Tensorflow-1.4.1 with Python3 and CUDA loaded.
        Check your $HOME/.tensorflowrc file is OK.

Wed Jul  4 16:10:57 2018
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 384.111                Driver Version: 384.111                   |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla P100-SXM2...  On   | 00000000:06:00.0 Off |                    0 |
| N/A   41C    P0   203W / 300W |   6865MiB / 16276MiB |     52%   E. Process |
+-------------------------------+----------------------+----------------------+
|   1  Tesla P100-SXM2...  On   | 00000000:07:00.0 Off |                    0 |
| N/A   39C    P0    36W / 300W |     10MiB / 16276MiB |      0%   E. Process |
+-------------------------------+----------------------+----------------------+
|   2  Tesla P100-SXM2...  On   | 00000000:0A:00.0 Off |                    0 |
| N/A   36C    P0    33W / 300W |     10MiB / 16276MiB |      0%   E. Process |
+-------------------------------+----------------------+----------------------+
|   3  Tesla P100-SXM2...  On   | 00000000:0B:00.0 Off |                    0 |
| N/A   36C    P0    33W / 300W |     10MiB / 16276MiB |      0%   E. Process |
+-------------------------------+----------------------+----------------------+
|   4  Tesla P100-SXM2...  On   | 00000000:85:00.0 Off |                    0 |
| N/A   37C    P0    34W / 300W |     10MiB / 16276MiB |      0%   E. Process |
+-------------------------------+----------------------+----------------------+
|   5  Tesla P100-SXM2...  On   | 00000000:86:00.0 Off |                    0 |
| N/A   31C    P0    33W / 300W |     10MiB / 16276MiB |      0%   E. Process |
+-------------------------------+----------------------+----------------------+
|   6  Tesla P100-SXM2...  On   | 00000000:89:00.0 Off |                    0 |
| N/A   38C    P0    36W / 300W |     10MiB / 16276MiB |      0%   E. Process |
+-------------------------------+----------------------+----------------------+
|   7  Tesla P100-SXM2...  On   | 00000000:8A:00.0 Off |                    0 |
| N/A   34C    P0    34W / 300W |     10MiB / 16276MiB |      0%   E. Process |
+-------------------------------+----------------------+----------------------+
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0     31780      C   python                                      6855MiB |
+-----------------------------------------------------------------------------+


Traceback (most recent call last):
  File "Classifier.py", line 249, in <module>
    buildmodel(input, msefile, classifierf, counter)
  File "Classifier.py", line 49, in buildmodel
    autoencoder = load_model('my_modela.h5')
  File "/jmain01/apps/python3/keras/2.1.4/lib/python3.6/site-packages/Keras-2.1.4-py3.6.egg/keras/models.py", line 246, in load_model
  File "/jmain01/apps/python3/keras/2.1.4/lib/python3.6/site-packages/Keras-2.1.4-py3.6.egg/keras/engine/topology.py", line 3189, in load_weights_from_hdf5_group
  File "/jmain01/apps/python3/keras/2.1.4/lib/python3.6/site-packages/Keras-2.1.4-py3.6.egg/keras/backend/tensorflow_backend.py", line 2370, in batch_set_value
  File "/jmain01/apps/python3/keras/2.1.4/lib/python3.6/site-packages/Keras-2.1.4-py3.6.egg/keras/backend/tensorflow_backend.py", line 176, in get_session
  File "/jmain01/apps/python3/tensorflow/1.4.1/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1482, in __init__
    super(Session, self).__init__(target, graph, config=config)
  File "/jmain01/apps/python3/tensorflow/1.4.1/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 622, in __init__
    self._session = tf_session.TF_NewDeprecatedSession(opts, status)
  File "/jmain01/apps/python3/tensorflow/1.4.1/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InternalError: Failed to create session.

```

 I might get lucky occasionally and run something, but this is happening most of the time.

**Comment by twinkarma** [comment]
Did you miss the following line from your batch script? 

```
echo "Using CUDA device " $CUDA_VISIBLE_DEVICES
```

The output above doesn't print out the device that CUDA in your batch job will use.

As for the SLURM error (https://github.com/jade-hpc-gpu/jade-hpc-gpu.github.io/issues/63#issuecomment-402504221), @Parker-A do you have any ideas?

**Comment by LiamATOS** [comment]
The slurm issue on dgj101 has now been resolved.

**Comment by llyhec** [comment]
My apologies, that was a problem with pasting. I managed to run some jobs yesterday evening/night, and I haven't had the error. Something else I am noticing with the cluster is, for the past several weeks I am unable to get anything running in the mornings - my jobs get executed usually after 4pm.  Is this a really busy period? Once they get running, I will keep you updated with the errors.

**Comment by llyhec** [comment]
Here is the error again: 


```
Python anaconda is now loaded in your environment.

python3/3.6.3(19):ERROR:150: Module 'python3/3.6.3' conflicts with the currently loaded module(s) 'python3/anaconda'
python3/3.6.3(19):ERROR:102: Tcl command execution failed: conflict python3


	CUDA-8.0 loaded


	Keras-2.1.4, Tensorflow-1.4.1 with Python3 and CUDA loaded.
	Check your $HOME/.tensorflowrc file is OK.

Fri Jul  6 11:37:44 2018       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 384.111                Driver Version: 384.111                   |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla P100-SXM2...  On   | 00000000:06:00.0 Off |                    0 |
| N/A   40C    P0    46W / 300W |   6865MiB / 16276MiB |      0%   E. Process |
+-------------------------------+----------------------+----------------------+
|   1  Tesla P100-SXM2...  On   | 00000000:07:00.0 Off |                    0 |
| N/A   39C    P0    36W / 300W |     10MiB / 16276MiB |      0%   E. Process |
+-------------------------------+----------------------+----------------------+
|   2  Tesla P100-SXM2...  On   | 00000000:0A:00.0 Off |                    0 |
| N/A   35C    P0    33W / 300W |     10MiB / 16276MiB |      0%   E. Process |
+-------------------------------+----------------------+----------------------+
|   3  Tesla P100-SXM2...  On   | 00000000:0B:00.0 Off |                    0 |
| N/A   35C    P0    33W / 300W |     10MiB / 16276MiB |      0%   E. Process |
+-------------------------------+----------------------+----------------------+
|   4  Tesla P100-SXM2...  On   | 00000000:85:00.0 Off |                    0 |
| N/A   37C    P0    34W / 300W |     10MiB / 16276MiB |      0%   E. Process |
+-------------------------------+----------------------+----------------------+
|   5  Tesla P100-SXM2...  On   | 00000000:86:00.0 Off |                    0 |
| N/A   30C    P0    33W / 300W |     10MiB / 16276MiB |      0%   E. Process |
+-------------------------------+----------------------+----------------------+
|   6  Tesla P100-SXM2...  On   | 00000000:89:00.0 Off |                    0 |
| N/A   38C    P0    36W / 300W |     10MiB / 16276MiB |      0%   E. Process |
+-------------------------------+----------------------+----------------------+
|   7  Tesla P100-SXM2...  On   | 00000000:8A:00.0 Off |                    0 |
| N/A   33C    P0    34W / 300W |     10MiB / 16276MiB |      0%   E. Process |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0     31780      C   python                                      6855MiB |
+-----------------------------------------------------------------------------+
Using CUDA device 0
2018-07-06 11:38:20.048257: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2018-07-06 11:38:20.100870: E tensorflow/core/common_runtime/direct_session.cc:170] Internal: failed initializing StreamExecutor for CUDA device ordinal 0: Internal: failed call to cuDevicePrimaryCtxRetain: CUDA_ERROR_INVALID_DEVICE
/jmain01/home/JAD002/dxt02/nxt42-dxt02/.conda/envs/testcon1/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
Train on 1080029 samples, validate on 1800049 samples
Traceback (most recent call last):
  File "teautocoder.py", line 154, in <module>
    buildmodel() 
  File "teautocoders.py", line 79, in buildmodel
    callbacks=[checkpointer, tensorboard]).history
  File "/jmain01/apps/python3/keras/2.1.4/lib/python3.6/site-packages/Keras-2.1.4-py3.6.egg/keras/engine/training.py", line 1712, in fit
  File "/jmain01/apps/python3/keras/2.1.4/lib/python3.6/site-packages/Keras-2.1.4-py3.6.egg/keras/engine/training.py", line 1153, in _fit_loop
  File "/jmain01/apps/python3/keras/2.1.4/lib/python3.6/site-packages/Keras-2.1.4-py3.6.egg/keras/callbacks.py", line 52, in set_model
  File "/jmain01/apps/python3/keras/2.1.4/lib/python3.6/site-packages/Keras-2.1.4-py3.6.egg/keras/callbacks.py", line 720, in set_model
  File "/jmain01/apps/python3/keras/2.1.4/lib/python3.6/site-packages/Keras-2.1.4-py3.6.egg/keras/backend/tensorflow_backend.py", line 176, in get_session
  File "/jmain01/apps/python3/tensorflow/1.4.1/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1482, in __init__
    super(Session, self).__init__(target, graph, config=config)
  File "/jmain01/apps/python3/tensorflow/1.4.1/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 622, in __init__
    self._session = tf_session.TF_NewDeprecatedSession(opts, status)
  File "/jmain01/apps/python3/tensorflow/1.4.1/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InternalError: Failed to create session.
```

**Comment by LiamATOS** [comment]
What node is this on?

**Comment by llyhec** [comment]
Node dgj419 - but, it happened on other nodes too. Can't remember their ids.

**Comment by LiamATOS** [comment]
whats your job script?

**Comment by llyhec** [comment]
I did not have this problem before, this has been happening for the past two weeks. 

```
#!/bin/bash
# set the number of nodes
#SBATCH --nodes=1
# set max wallclock time
#SBATCH --time=00:30:00
# set name of job
#SBATCH --job-name=A30
# set number of GPUs
#SBATCH --gres=gpu:1

module load python3/anaconda
source activate testcon1
module load keras/2.1.4
nvidia-smi
echo "Using CUDA device" $CUDA_VISIBLE_DEVICES
python teautocoder.py

```

**Comment by llyhec** [comment]
I am having the same problem again, both on nodes dgj223 and dgj419. Unable run anything today. I submitted about 10 jobs, I get the same error. Is there a way to login to another nodes, I tried ssh dgj324, but, it doesn't recognise my login password.

**Comment by LiamATOS** [comment]
223 and 419 are the login nodes, I need to know the nodes your job is being allocated when you submit?

**Comment by llyhec** [comment]
Sorry about that. I am currently running what I couldn't run this weekend, and they are running on node dgj101. I will let you know the node when I get the error again.

**Comment by agniszczotka** [comment]
I encounter the same problem. 
It is related to not updated drivers for tensorflow.
