### ISSUE TITLE
Upper limit on matrix size when multiplying matrices

### ISSUE THREAD

**Issue by gtinchev** [jade-hpc-gpu/jade-hpc-gpu.github.io#70]
Is there an upper limit when multiplying two matrices via tf.matmul with cuda blas on JADE? I'm using tensorflow 18.04-py3 container on a small partition (tried devel and big as well, same result).

Currently I do not have the same issue on my machine (TITAN Xp 12GB VRAM)

How to reproduce the issue:

Code:

```
import tensorflow as tf

a = tf.random_uniform((65536,8,8))
b = tf.random_uniform((65536,8,24))
c = tf.matmul(a,b)

sess = tf.Session()
r = sess.run([c])

print(r)
```

Note that if you change 65536 (=256^2) to 16384 (=128^2) - this operation runs fine on JADE. 

Error:

```
2018-07-30 14:01:49.146155: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1041] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 15128 MB memory) -> physical GPU (device: 0, name: Tesla P100-SXM2-16GB, pci bus id: 0000:0a:00.0, compute capability: 6.0)
2018-07-30 14:01:49.188951: E tensorflow/stream_executor/cuda/cuda_blas.cc:673] failed to run cuBLAS routine cublasGemmBatchedEx: CUBLAS_STATUS_NOT_SUPPORTED
2018-07-30 14:01:49.188985: E tensorflow/stream_executor/cuda/cuda_blas.cc:2608] Internal: failed BLAS call, see log for details
/home_directory/.local/lib/python3.5/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1327, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1312, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1420, in _call_tf_sessionrun
    status, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py", line 516, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InternalError: Blas xGEMMBatched launch failed : a.shape=[65536,8,8], b.shape=[65536,8,24], m=8, n=24, k=8, batch_size=65536
	 [[Node: MatMul = BatchMatMul[T=DT_FLOAT, adj_x=false, adj_y=false, _device="/job:localhost/replica:0/task:0/device:GPU:0"](random_uniform, random_uniform_1)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home_directory/code/debug_jade_tf.py", line 17, in <module>
    r = sess.run([c])
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 905, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1140, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1321, in _do_run
    run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1340, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InternalError: Blas xGEMMBatched launch failed : a.shape=[65536,8,8], b.shape=[65536,8,24], m=8, n=24, k=8, batch_size=65536
	 [[Node: MatMul = BatchMatMul[T=DT_FLOAT, adj_x=false, adj_y=false, _device="/job:localhost/replica:0/task:0/device:GPU:0"](random_uniform, random_uniform_1)]]

Caused by op 'MatMul', defined at:
  File "/home_directory/code/debug_jade_tf.py", line 5, in <module>
    c = tf.matmul(a,b)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/math_ops.py", line 2071, in matmul
    a, b, adj_x=adjoint_a, adj_y=adjoint_b, name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/gen_math_ops.py", line 1236, in batch_mat_mul
    "BatchMatMul", x=x, y=y, adj_x=adj_x, adj_y=adj_y, name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 3290, in create_op
    op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 1654, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InternalError (see above for traceback): Blas xGEMMBatched launch failed : a.shape=[65536,8,8], b.shape=[65536,8,24], m=8, n=24, k=8, batch_size=65536
	 [[Node: MatMul = BatchMatMul[T=DT_FLOAT, adj_x=false, adj_y=false, _device="/job:localhost/replica:0/task:0/device:GPU:0"](random_uniform, random_uniform_1)]]
```

Is it possible to lift this limit? I'm looking currently at something between 512^2 to 4096^2.

**Comment by gtinchev** [comment]
Hi,

**Comment by gtinchev** [comment]
Heya, any info on this, please?

**Comment by twinkarma** [comment]
Hi @gtinchev,

Can you post your batch script aswell, or if it's an interactive session, what parameters are you using with srun?

**Comment by gtinchev** [comment]
Hi @twinkarma,

```
#!/bin/bash

# set the partition where the job will run; eg k20 or k40
#SBATCH --partition=small
 
# set the number of nodes
#SBATCH --nodes=1
 
# set the number of GPU cards to use per node
#SBATCH --gres=gpu:1
 
# set max wallclock time
#SBATCH --time=24:00:00
 
# set name of job
#SBATCH --job-name=debug_tf
 
# mail alert at start, end and abortion of execution
#SBATCH --mail-type=ALL
 
# send mail to this address
#SBATCH --mail-user=XXX@XXX.XXX
 
#SBATCH --output=debug_tf.txt


execute_this="python3 /home_directory/code/debug_jade_tf.py"
# always load outside of srun
module load cuda/9.0
module load hdf5/1.10.1
module load python3/3.5.2

rm temp_launch_scipt.sh


echo "export PYTHONPATH=\"/home_directory/.local/lib/python3.5/site-packages/:$PYTHONPATH\"" >> temp_launch_scipt.sh

echo ${execute_this} >> temp_launch_scipt.sh

chmod +x temp_launch_scipt.sh

/jmain01/apps/docker/tensorflow-batch -v 18.04-py3 -c ./temp_launch_scipt.sh

#rm temp_launch_scipt.sh
```

As you have probably gathered from the above script, the contents of "temp_launch_script.sh" is as follows (gets generated every time):

```
export PYTHONPATH="/home_directory/.local/lib/python3.5/site-packages/:/home_directory/.local/lib/python3.5/site-packages/:"
python3 /home_directory/code/debug_jade_tf.py
```

Here debug_jade_tf.py is the same script as above:

```
import tensorflow as tf

a = tf.random_uniform((65536,8,8))
b = tf.random_uniform((65536,8,24))
c = tf.matmul(a,b)

sess = tf.Session()
r = sess.run([c])

print(r)
```

**Comment by twinkarma** [comment]
I've not been able to get the docker image working for your example but I am able to run the code example using a version of tensorflow installed through anaconda:

To create a virtual python environment
```
module load python3/anaconda
module load cuda/9.0

# Create a virtual environment called my_tensorflow_env and activate it
conda create -n my_tensorflow_env python=3.6
source activate my_tensorflow_env

# Install tensorflow 1.12 (1.13 requires cuda 10 which is not installed on JADE for now)
pip install tensorflow-gpu==1.12

# Run the script
python mytestscript.py
```

Everytime afterwards:

```
module load python3/anaconda
module load cuda/9.0

# Activate your environment
source activate my_tensorflow_env

# Run your script
python myscript.py
```
