### ISSUE TITLE
Unable to use tensorflow-GPU. Error: CUDA driver version is insufficient for CUDA runtime version

### ISSUE THREAD

**Issue by vandana-rajan** [jade-hpc-gpu/jade-hpc-gpu.github.io#81]
I have created an anaconda (python2.7) virtual environment and installed keras (GPU version). But when I try to use the GPU version, it throws the following error

>> cudaGetDevice() failed. Status: CUDA driver version is insufficient for CUDA runtime version

The complete error message is as shown below

>> 2018-10-24 15:39:51.063757: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA

>>2018-10-24 15:39:51.749144: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1411] Found device 0 with properties: 
name: Tesla P100-SXM2-16GB major: 6 minor: 0 memoryClockRate(GHz): 1.4805
pciBusID: 0000:0a:00.0
totalMemory: 15.89GiB freeMemory: 15.60GiB

>>2018-10-24 15:39:51.749217: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1490] Adding visible gpu devices: 0

>> Traceback (most recent call last):
  File "test.py", line 2, in <module>
    print(device_lib.list_local_devices())
  File "/jmain01/home/JAD007/txk02/vxr25-txk02/.conda/envs/MyPython2.7KerasGPU/lib/python2.7/site-packages/tensorflow/python/client/device_lib.py", line 41, in list_local_devices
    for s in pywrap_tensorflow.list_devices(session_config=session_config)
  File "/jmain01/home/JAD007/txk02/vxr25-txk02/.conda/envs/MyPython2.7KerasGPU/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 1711, in list_devices
    return ListDevices(status)
  File "/jmain01/home/JAD007/txk02/vxr25-txk02/.conda/envs/MyPython2.7KerasGPU/lib/python2.7/site-packages/tensorflow/python/framework/errors_impl.py", line 526, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InternalError: cudaGetDevice() failed. Status: CUDA driver version is insufficient for CUDA runtime version

**Comment by vandana-rajan** [comment]
This got resolved when I used tensorflow version 1.9.0. Previously I was using version 1.11
